//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Banking_Client.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employees", Namespace="http://schemas.datacontract.org/2004/07/E_Banking")]
    [System.SerializableAttribute()]
    public partial class Employees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptId {
            get {
                return this.DeptIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptIdField, value) != true)) {
                    this.DeptIdField = value;
                    this.RaisePropertyChanged("DeptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptName {
            get {
                return this.DeptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNameField, value) != true)) {
                    this.DeptNameField = value;
                    this.RaisePropertyChanged("DeptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpId {
            get {
                return this.EmpIdField;
            }
            set {
                if ((this.EmpIdField.Equals(value) != true)) {
                    this.EmpIdField = value;
                    this.RaisePropertyChanged("EmpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryField, value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/E_Banking")]
    [System.SerializableAttribute()]
    public partial class ExceptionMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorMessageOfActionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorMessageOfAction {
            get {
                return this.errorMessageOfActionField;
            }
            set {
                if ((object.ReferenceEquals(this.errorMessageOfActionField, value) != true)) {
                    this.errorMessageOfActionField = value;
                    this.RaisePropertyChanged("errorMessageOfAction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertEmpDetails", ReplyAction="http://tempuri.org/IService1/InsertEmpDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(E_Banking_Client.ServiceReference2.ExceptionMessage), Action="http://tempuri.org/IService1/InsertEmpDetailsExceptionMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/E_Banking")]
        void InsertEmpDetails(E_Banking_Client.ServiceReference2.Employees eDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertEmpDetails", ReplyAction="http://tempuri.org/IService1/InsertEmpDetailsResponse")]
        System.Threading.Tasks.Task InsertEmpDetailsAsync(E_Banking_Client.ServiceReference2.Employees eDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployees", ReplyAction="http://tempuri.org/IService1/GetEmployeesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(E_Banking_Client.ServiceReference2.ExceptionMessage), Action="http://tempuri.org/IService1/GetEmployeesExceptionMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/E_Banking")]
        E_Banking_Client.ServiceReference2.Employees[] GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployees", ReplyAction="http://tempuri.org/IService1/GetEmployeesResponse")]
        System.Threading.Tasks.Task<E_Banking_Client.ServiceReference2.Employees[]> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEmpDetails", ReplyAction="http://tempuri.org/IService1/UpdateEmpDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(E_Banking_Client.ServiceReference2.ExceptionMessage), Action="http://tempuri.org/IService1/UpdateEmpDetailsExceptionMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/E_Banking")]
        void UpdateEmpDetails(E_Banking_Client.ServiceReference2.Employees eDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEmpDetails", ReplyAction="http://tempuri.org/IService1/UpdateEmpDetailsResponse")]
        System.Threading.Tasks.Task UpdateEmpDetailsAsync(E_Banking_Client.ServiceReference2.Employees eDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmpDetails", ReplyAction="http://tempuri.org/IService1/DeleteEmpDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(E_Banking_Client.ServiceReference2.ExceptionMessage), Action="http://tempuri.org/IService1/DeleteEmpDetailsExceptionMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/E_Banking")]
        void DeleteEmpDetails(int EmpId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmpDetails", ReplyAction="http://tempuri.org/IService1/DeleteEmpDetailsResponse")]
        System.Threading.Tasks.Task DeleteEmpDetailsAsync(int EmpId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : E_Banking_Client.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<E_Banking_Client.ServiceReference2.IService1>, E_Banking_Client.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertEmpDetails(E_Banking_Client.ServiceReference2.Employees eDetails) {
            base.Channel.InsertEmpDetails(eDetails);
        }
        
        public System.Threading.Tasks.Task InsertEmpDetailsAsync(E_Banking_Client.ServiceReference2.Employees eDetails) {
            return base.Channel.InsertEmpDetailsAsync(eDetails);
        }
        
        public E_Banking_Client.ServiceReference2.Employees[] GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<E_Banking_Client.ServiceReference2.Employees[]> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public void UpdateEmpDetails(E_Banking_Client.ServiceReference2.Employees eDetails) {
            base.Channel.UpdateEmpDetails(eDetails);
        }
        
        public System.Threading.Tasks.Task UpdateEmpDetailsAsync(E_Banking_Client.ServiceReference2.Employees eDetails) {
            return base.Channel.UpdateEmpDetailsAsync(eDetails);
        }
        
        public void DeleteEmpDetails(int EmpId) {
            base.Channel.DeleteEmpDetails(EmpId);
        }
        
        public System.Threading.Tasks.Task DeleteEmpDetailsAsync(int EmpId) {
            return base.Channel.DeleteEmpDetailsAsync(EmpId);
        }
    }
}
